// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbVMlpgmtlLdVIICAXMlUYK1SbX7KSDNQ',
    appId: '1:565386347531:web:ef73ba76ea61ae2157f30e',
    messagingSenderId: '565386347531',
    projectId: 'budgettracker-e147f',
    authDomain: 'budgettracker-e147f.firebaseapp.com',
    storageBucket: 'budgettracker-e147f.appspot.com',
    measurementId: 'G-77G2V0RJH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvhBFzB_UCPhcKgGNoRno3ZhqSRGDV0Y',
    appId: '1:565386347531:android:02b2ee4f4be7cab657f30e',
    messagingSenderId: '565386347531',
    projectId: 'budgettracker-e147f',
    storageBucket: 'budgettracker-e147f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF98QiakeBNAtq2kOuIRKNTJFXF3M48b8',
    appId: '1:565386347531:ios:89c69e884567fae457f30e',
    messagingSenderId: '565386347531',
    projectId: 'budgettracker-e147f',
    storageBucket: 'budgettracker-e147f.appspot.com',
    iosClientId: '565386347531-teuneb9k4g98ku0l8k6875hdg35v7ecu.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF98QiakeBNAtq2kOuIRKNTJFXF3M48b8',
    appId: '1:565386347531:ios:f99b2b55365dd1ea57f30e',
    messagingSenderId: '565386347531',
    projectId: 'budgettracker-e147f',
    storageBucket: 'budgettracker-e147f.appspot.com',
    iosClientId: '565386347531-p3fkltg257nvqlabvc3mofuhghul91t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
